server:
  port: 8087
  tomcat:
    max-connections: 10000
    accept-count: 10000
    threads:
      max: 10_000
      min-spare: 1000

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:~/wisebits/demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: ${project.name}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
    mapper:
      accept-case-insensitive-enums: true

logging:
  level:
    ROOT: INFO